apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp1-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template: 
    metadata: # Dictionary
      labels: # Dictionary  
        app: nginx    
    spec:
      containers: # List
      - name: myapp1-container
        image: nginx
        ports:
        - containerPort: 80
